create table sensor (
                        sensor_id int generated by default as identity primary key,
                        sensor_name varchar(100) not null unique
);
create table measurement (
                             measurement_id int generated by default as identity primary key,
                             measurement_value FLOAT not null check ( measurement_value > -100.0 and measurement_value < 100.0 ),
                             measurement_is_raining BOOLEAN NOT NULL,
                             sensor_id int not null references sensor(sensor_id) on delete cascade,
                             a_current_time timestamp not null
);